server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect




  security:
    oauth2:

      resourceserver:
        jwt:
          issuer-uri: https://trial-8985060.okta.com/oauth2/default

      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oa11v55eedfgwBif698
            client-secret: xAiuOfYNNCsim-KtQYcBsu24GGYzUvFsBu30lIgGokfNjR6mbI_xha57YN-g7l1w

        provider:
          okta:
            issuer-uri: https://trial-8985060.okta.com/oauth2/default

eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true


resilience4j:
  circuitbreaker:
    circuitBreakerAspectOrder: 1
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 7
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    retryAspectOrder: 2
    instances:
      ratingHotelRetry:
        maxAttempts: 3
        waitDuration: 2s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2


#Okta configuration for API Gateway
okta:
  oauth2:
    issuer: https://trial-8985060.okta.com/oauth2/default
    audience: api://default

logging:
  level:
    org.springframework.security: DEBUG



