server:
  port: 8082

spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:postgresql://localhost:5432/hotelservice
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instances:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#Okta configuration for API Gateway
okta:
  oauth2:
    issuer: https://trial-8985060.okta.com/oauth2/default
    audience: api://default

